version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    command: ["npm", "start"]

  mysql:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_tp
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
